import type {EditorThemeClasses} from 'lexical';

const theme: EditorThemeClasses = {
  autocomplete: 'text-gray-400',
  blockCursor: 'block pointer-events-none absolute after:content-[""] after:block after:absolute after:-top-0.5 after:w-5 after:border-t after:border-black after:animate-pulse',
  characterLimit: 'inline bg-red-200',
  code: 'bg-gray-50 font-mono block py-3 px-4 leading-relaxed text-sm my-4 overflow-x-auto relative border border-gray-200 rounded-md',
  codeHighlight: {
    atrule: 'text-blue-600',
    attr: 'text-blue-600',
    boolean: 'text-purple-600',
    builtin: 'text-green-600',
    cdata: 'text-gray-500',
    char: 'text-green-600',
    class: 'text-pink-600',
    'class-name': 'text-pink-600',
    comment: 'text-gray-500',
    constant: 'text-purple-600',
    deleted: 'bg-red-100 text-red-800',
    doctype: 'text-gray-500',
    entity: 'text-amber-600',
    function: 'text-pink-600',
    important: 'text-orange-500',
    inserted: 'bg-green-100 text-green-800',
    keyword: 'text-blue-600',
    namespace: 'text-orange-500',
    number: 'text-purple-600',
    operator: 'text-amber-600',
    prolog: 'text-gray-500',
    property: 'text-purple-600',
    punctuation: 'text-gray-600',
    regex: 'text-orange-500',
    selector: 'text-green-600',
    string: 'text-green-600',
    symbol: 'text-purple-600',
    tag: 'text-purple-600',
    unchanged: 'bg-gray-100',
    url: 'text-blue-600 underline',
    variable: 'text-orange-500',
  },
  embedBlock: {
    base: 'select-none',
    focus: 'outline outline-2 outline-blue-500',
  },
  hashtag: 'bg-blue-100 border-b border-blue-300 px-1 rounded-sm',
  heading: {
    h1: 'text-3xl font-bold text-gray-900 mt-6 mb-4 leading-tight',
    h2: 'text-2xl font-semibold text-gray-800 mt-5 mb-3 leading-tight',
    h3: 'text-xl font-semibold text-gray-800 mt-4 mb-2 leading-tight',
    h4: 'text-lg font-medium text-gray-800 mt-3 mb-2 leading-tight',
    h5: 'text-base font-medium text-gray-800 mt-2 mb-1 leading-tight',
    h6: 'text-sm font-medium text-gray-700 mt-2 mb-1 leading-tight',
  },
  hr: 'border-none my-6 h-px bg-gray-300',
  hrSelected: 'outline outline-2 outline-blue-500 select-none',
  image: 'max-w-full h-auto block mx-auto my-4',
  indent: 'ml-8',
  inlineImage: 'inline-block max-w-full h-auto',
  layoutContainer: 'grid gap-4 my-4',
  layoutItem: 'border border-dashed border-gray-300 p-4 min-w-0',
  link: 'text-blue-600 underline hover:text-blue-800 cursor-pointer',
  list: {
    checklist: 'list-none',
    listitem: 'mb-1',
    listitemChecked: 'relative pl-6 mb-1 line-through text-gray-500 before:content-["✓"] before:absolute before:left-0 before:text-green-600 before:font-bold',
    listitemUnchecked: 'relative pl-6 mb-1 before:content-["☐"] before:absolute before:left-0 before:text-gray-400',
    nested: {
      listitem: 'mb-1',
    },
    olDepth: [
      'list-decimal ml-6 pl-2',
      'list-[upper-alpha] ml-6 pl-2',
      'list-[lower-alpha] ml-6 pl-2',
      'list-[upper-roman] ml-6 pl-2',
      'list-[lower-roman] ml-6 pl-2',
    ],
    ul: 'list-disc ml-6 pl-2',
  },
  ltr: 'text-left',
  mark: 'bg-yellow-200 px-1 rounded-sm',
  markOverlap: 'bg-yellow-300 px-1 rounded-sm',
  paragraph: 'mb-4 leading-relaxed text-gray-900',
  quote: 'border-l-4 border-gray-400 pl-4 ml-4 my-4 italic text-gray-700 bg-gray-50 py-2',
    rtl: 'text-right',
  specialText: 'bg-yellow-300 font-semibold px-1 rounded-sm',
  tab: 'inline-block w-8',
  table: 'border-collapse w-full my-6 border border-gray-300',
  tableAddColumns: 'absolute bg-gray-200 h-full border-0 cursor-pointer hover:bg-blue-200',
  tableAddRows: 'absolute w-full bg-gray-200 border-0 cursor-pointer hover:bg-blue-200',
  tableAlignment: {
    center: 'mx-auto',
    right: 'ml-auto',
  },
  tableCell: 'border border-gray-300 p-3 align-top text-left min-w-0',
  tableCellActionButton: 'bg-gray-200 border-0 rounded-full w-5 h-5 text-gray-700 cursor-pointer hover:bg-gray-300',
  tableCellActionButtonContainer: 'absolute right-1 top-1 z-10',
  tableCellHeader: 'bg-gray-100 font-semibold text-gray-800 border-b-2 border-gray-400',
  tableCellResizer: 'absolute -right-1 h-full w-2 cursor-col-resize z-10 top-0',
  tableCellSelected: 'bg-blue-100 relative',
  tableFrozenColumn: '[&_tr>td:first-child]:bg-white [&_tr>td:first-child]:sticky [&_tr>td:first-child]:left-0 [&_tr>th:first-child]:bg-gray-100 [&_tr>th:first-child]:sticky [&_tr>th:first-child]:left-0',
  tableFrozenRow: '[&_tr:first-child>td]:bg-white [&_tr:first-child>td]:sticky [&_tr:first-child>td]:top-0 [&_tr:first-child>th]:bg-gray-100 [&_tr:first-child>th]:sticky [&_tr:first-child>th]:top-0',
  tableRowStriping: '[&_tr:nth-child(even)]:bg-gray-50',
  tableScrollableWrapper: 'overflow-x-auto my-6',
  tableSelected: 'outline outline-2 outline-blue-500',
  tableSelection: '[&_*::selection]:bg-blue-100',
  text: {
    bold: 'font-bold',
    capitalize: 'capitalize',
    code: 'bg-gray-100 px-2 py-1 rounded font-mono text-sm',
    highlight: 'bg-yellow-200 px-1 rounded-sm',
    italic: 'italic',
    lowercase: 'lowercase',
    strikethrough: 'line-through',
    subscript: 'text-sm align-sub',
    superscript: 'text-sm align-super',
    underline: 'underline',
    underlineStrikethrough: 'underline line-through',
    uppercase: 'uppercase',
  },
};

export default theme;